name: Shooter
main: com.github.ucchyocean.Shooter
version: 1.1.0
author: ucchy
description: Shooter is the magic battle item.
commands:
  shooter:
    description: Shooter is the magic battle item.
    aliases: sh
    usage: |
           /<command> get [level] - Get new shooter.
           /<command> give (player) [level] - Give new shooter.
    permission: shooter
    permission-message: You don't have permission "<permission>".
permissions:
  shooter.get:
    description: Shooter command permission.
    default: op
  shooter.give:
    description: Shooter command permission.
    default: op
  shooter.action:
    description: Shooter permission.
    default: false
  shooter.action.rideon.*:
    description: Shooter permission.
    default: false
    children:
      shooter.action.rideon.horse: true
      shooter.action.rideon.pig: true
      shooter.action.rideon.boat: true
      shooter.action.rideon.minecart: true
